services:
  - type: web
    name: grema-store-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run prisma:generate && npm run build && npm run prisma:migrate:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: grema-store-db
          property: connectionString
      - key: JWT_SECRET
        value: 4fc122962280297d55cc43b3f8e4612c1e2e303707b1e0c91cf8d710ef8448d35d2ab631d82289e6bc111d28d3d9c8ade11517978a4a2b6ecc470dc0b8c03c88
      - key: FRONTEND_URL
        value: https://www.grema-store.com
      - key: CORS_ORIGIN
        value: https://www.grema-store.com
      - key: LOG_LEVEL
        value: warn
      - key: API_VERSION
        value: v1
      - key: WHATSAPP_ACCESS_TOKEN
        value: EAAJwmuBK4PwBO7ZCNvOuKjjTIHylqXiS7ZBefKGhBs1NKVEQKN7NNPkgb3x0A9uDZAYVgoKL11IQnkvGs4xBD1qQBRWYeLZBJKCU4xlSygOSx29kZCl1HNUZCZCiioOCKkoxfR4Os4POt3cPwvBpqP7hF4sf08aLumBmz2SZCyuQkQ8dcXQcLqCEGZCjRlABaxJKhZBZCeeoaRwsidfqRCD7QtvfM4mu67L
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: 638623259330908
      - key: WHATSAPP_API_VERSION
        value: v22.0
      - key: WHATSAPP_WEBHOOK_TOKEN
        value: 1694674998069789
      - key: CLOUDINARY_CLOUD_NAME
        value: dskeh6ivy-dev
      - key: CLOUDINARY_API_KEY
        value: 739451535494621
      - key: CLOUDINARY_API_SECRET
        value: iGP4Mvu6gPCh4IRd9vtINL2sTrQ
      - key: IMAGEKIT_PUBLIC_KEY_PICS
        value: public_er76QuOxBA7U8X7se686ICHNFqU=
      - key: IMAGEKIT_PRIVATE_KEY_PICS
        value: private_+yEvVTyEzhFFh5hsy8absIups9w=
      - key: IMAGEKIT_URL_ENDPOINT_PICS
        value: https://ik.imagekit.io/wtelcc7rn
      - key: IMAGEKIT_PUBLIC_KEY_OTHERS
        value: public_JS8STG4TIYPWHJLzOu5agCd4s1M=
      - key: IMAGEKIT_PRIVATE_KEY_OTHERS
        value: private_AF7rqKr7Xze9GHryudCB8sT+Nwo=
      - key: IMAGEKIT_URL_ENDPOINT_OTHERS
        value: https://ik.imagekit.io/xj7y5uqcr
      - key: GOOGLE_CLIENT_ID
        value: 298483544989-79j1970tm0q2i8jjrn1rq4r7mrkptpgg.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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e

databases:
  - name: grema-store-db
    plan: free
